version: '3'

services:
  db:
    image: mysql:8.0.41
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - dbdata:/var/lib/mysql
    restart: always

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${CODEBOX_DB_ROOT_PASSWORD:-password}
    labels:
      - com.codebox.port.phpmyadmin=80
      - com.codebox.port.phpmyadmin.public=false

  app:
    build:
        context: .
        args:
            USER_NAME: ${CODEBOX_WORKSPACE_OWNER_FIRST_NAME:-}
            USER_EMAIL: ${CODEBOX_WORKSPACE_OWNER_EMAIL:-}
            USER_FIRST_NAME: ${CODEBOX_WORKSPACE_OWNER_FIRST_NAME:-}
            USER_LAST_NAME: ${CODEBOX_WORKSPACE_OWNER_LAST_NAME:-}
    stdin_open: true
    tty: true
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - workspace:/home/${CODEBOX_WORKSPACE_OWNER_FIRST_NAME:-}
    labels:
        - com.codebox.user=${CODEBOX_WORKSPACE_OWNER_FIRST_NAME:-}

volumes:
  dbdata:
