version: '3'

services:
  redis:
    image: redis:7.4.1
    restart: always

  db:
    image: mysql:8.0.41
    environment:
      MYSQL_ROOT_PASSWORD: ${CODEBOX_DB_ROOT_PASSWORD:-password}
      MYSQL_DATABASE: ${CODEBOX_DB_NAME:-codebox}
      MYSQL_USER: ${CODEBOX_DB_USER:-codebox}
      MYSQL_PASSWORD: ${CODEBOX_DB_PASSWORD:-password}
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - codeboxdb:/var/lib/mysql
    restart: always

  codebox:
    image: dadebia/codebox:${CODEBOX_VERSION:-latest}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - ${CODEBOX_PORT:-12800}:8000
    volumes:
      - codeboxdata:/codebox/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CODEBOX_EXTERNAL_URL=${CODEBOX_EXTERNAL_URL:-https://codebox.example.com}
      - CODEBOX_WILDCARD_DOMAIN=${CODEBOX_WILDCARD_DOMAIN:-codebox.example.com}
      - CODEBOX_USE_GRAVATAR=true
      - CODEBOX_USE_SUBDOMAINS=true
      - CODEBOX_DB_NAME=${CODEBOX_DB_NAME:-codebox}
      - CODEBOX_DB_USER=${CODEBOX_DB_USER:-codebox}
      - CODEBOX_DB_PASSWORD=${CODEBOX_DB_PASSWORD:-password}
    restart: always

volumes:
  codeboxdb:
  codeboxdata:
