// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "MIT",
            "url": "https://mit-license.org"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/auth/login": {
            "post": {
                "description": "Login",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "Credentials",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.LoginRequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/serializers.TokenSerializer"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/logout": {
            "post": {
                "description": "Logout",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Logout",
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/api/v1/auth/signup": {
            "post": {
                "description": "Signup",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Signup",
                "parameters": [
                    {
                        "description": "Credentials",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.SignUpRequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/serializers.UserSerializer"
                        }
                    }
                }
            }
        },
        "/api/v1/templates": {
            "get": {
                "description": "List all templates",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "List templates",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.WorkspaceTemplate"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a template",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "Create template",
                "parameters": [
                    {
                        "description": "Template data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/templates.CreateTemplateRequestBody"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.WorkspaceTemplate"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/templates-by-name/:name": {
            "get": {
                "description": "Retrieve a template by name",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "Retrieve template by name",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.WorkspaceTemplate"
                        }
                    }
                }
            }
        },
        "/api/v1/templates/:id": {
            "get": {
                "description": "Retrieve a template by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "Retrieve template by id",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.WorkspaceTemplate"
                        }
                    }
                }
            }
        },
        "/api/v1/templates/:templateId": {
            "put": {
                "description": "Update a template",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "Update template",
                "parameters": [
                    {
                        "description": "Template data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/templates.UpdateTemplateRequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.WorkspaceTemplate"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a template",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "Delete template",
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.WorkspaceTemplate"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/templates/:templateId/latest-version": {
            "get": {
                "description": "Retrieve the latest template version",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "Retrieve the latest template version",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.WorkspaceTemplateVersion"
                        }
                    }
                }
            }
        },
        "/api/v1/templates/:templateId/versions": {
            "get": {
                "description": "List all template versions by template",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "List template versions by template",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.WorkspaceTemplateVersion"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/templates/:templateId/versions/:templateId/entries": {
            "post": {
                "description": "Create new template version entry",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "Create new template version entry",
                "parameters": [
                    {
                        "description": "Template version entry data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/templates.CreateTemplateVersionEntryRequestBody"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/targz.TarEntry"
                        }
                    }
                }
            }
        },
        "/api/v1/templates/:templateId/versions/:templateId/entries/:path": {
            "put": {
                "description": "Updates a template version entry",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "Updates a template version entry",
                "parameters": [
                    {
                        "description": "Template version entry data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/templates.UpdateTemplateVersionEntryRequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/targz.TarEntry"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete template version entry",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "Delete template version entry",
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/api/v1/templates/:templateId/versions/:versionId": {
            "get": {
                "description": "Retrieve template version by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "Retrieve template version by id",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.WorkspaceTemplateVersion"
                        }
                    }
                }
            },
            "put": {
                "description": "Update a template version",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "Update a template version",
                "parameters": [
                    {
                        "description": "Template version data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/templates.UpdateTemplateVersionRequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.WorkspaceTemplateVersion"
                        }
                    }
                }
            }
        },
        "/api/v1/templates/:templateId/versions/:versionId/entries": {
            "get": {
                "description": "List template version entries",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "List template version entries",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/targz.TarTreeItem"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/templates/:templateId/versions/:versionId/entries/:path": {
            "get": {
                "description": "Retrieve template version entry",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "Retrieve template version entry",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/targz.TarEntry"
                        }
                    }
                }
            }
        },
        "/api/v1/templates/:templateId/workspaces": {
            "get": {
                "description": "List workspaces that use a template",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "List workspaces that use a template",
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Workspace"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/workspace": {
            "get": {
                "description": "List workspaces created by the current user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Workspaces"
                ],
                "summary": "List workspaces",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/serializers.WorkspaceSerializer"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new workspace",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Workspaces"
                ],
                "summary": "Create a workspace",
                "parameters": [
                    {
                        "description": "Data for creating a workspace",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/workspaces.CreateWorkspaceRequestBody"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/serializers.WorkspaceSerializer"
                        }
                    }
                }
            }
        },
        "/api/v1/workspace-types": {
            "get": {
                "description": "List workspace types",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Workspaces"
                ],
                "summary": "List workspace types",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/serializers.WorkspaceTypeSerializer"
                        }
                    }
                }
            }
        },
        "/api/v1/workspace/:id": {
            "get": {
                "description": "Retrieve a workspace by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Workspaces"
                ],
                "summary": "Retrieve workspace by id",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/serializers.WorkspaceSerializer"
                        }
                    }
                }
            },
            "put": {
                "description": "Update a workspace",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Workspaces"
                ],
                "summary": "Update a workspace",
                "parameters": [
                    {
                        "description": "Data to update a workspace",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/workspaces.CreateWorkspaceRequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/serializers.WorkspaceSerializer"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a workspace",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Workspaces"
                ],
                "summary": "Delete a workspace",
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/api/v1/workspace/:id/start": {
            "post": {
                "description": "Start a workspace",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Workspaces"
                ],
                "summary": "Start a workspace",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/serializers.WorkspaceSerializer"
                        }
                    }
                }
            }
        },
        "/api/v1/workspace/:id/stop": {
            "post": {
                "description": "Stop a workspace",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Workspaces"
                ],
                "summary": "Stop a workspace",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/serializers.WorkspaceSerializer"
                        }
                    }
                }
            }
        },
        "/api/v1/workspace/:workspaceId/logs": {
            "get": {
                "description": "Retrieve workspace logs",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Workspaces"
                ],
                "summary": "Retrieve workspace logs",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/v1/workspace/:workspaceId/update-config": {
            "post": {
                "description": "Update workspace configuration, retrieving the configuration files from the git repository or template",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Workspaces"
                ],
                "summary": "Update workspace configuration",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    },
    "definitions": {
        "auth.LoginRequestBody": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "remember_me": {
                    "type": "boolean"
                }
            }
        },
        "auth.SignUpRequestBody": {
            "type": "object",
            "required": [
                "email",
                "first_name",
                "last_name",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "models.GitWorkspaceSource": {
            "type": "object",
            "properties": {
                "config_file_relative_path": {
                    "description": "path of the configuration files relative to the root of the repo",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "ref_name": {
                    "type": "string"
                },
                "repository_url": {
                    "type": "string"
                }
            }
        },
        "models.Group": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "models.Runner": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "last_contact": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "public_url": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "use_public_url": {
                    "type": "boolean"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "models.User": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "groups": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Group"
                    }
                },
                "is_superuser": {
                    "type": "boolean"
                },
                "is_template_manager": {
                    "type": "boolean"
                },
                "last_name": {
                    "type": "string"
                }
            }
        },
        "models.Workspace": {
            "type": "object",
            "properties": {
                "config_source": {
                    "description": "template/git",
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "environment_variables": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "git_source": {
                    "$ref": "#/definitions/models.GitWorkspaceSource"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "runner": {
                    "$ref": "#/definitions/models.Runner"
                },
                "status": {
                    "type": "string"
                },
                "template_version": {
                    "$ref": "#/definitions/models.WorkspaceTemplateVersion"
                },
                "type": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/models.User"
                }
            }
        },
        "models.WorkspaceTemplate": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "icon": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "models.WorkspaceTemplateVersion": {
            "type": "object",
            "properties": {
                "config_file_relative_path": {
                    "type": "string"
                },
                "edited_on": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "published": {
                    "type": "boolean"
                },
                "published_on": {
                    "type": "string"
                },
                "template": {
                    "type": "integer"
                }
            }
        },
        "serializers.GitWorkspaceSourceSerializer": {
            "type": "object",
            "properties": {
                "config_file_relative_path": {
                    "type": "string"
                },
                "ref_name": {
                    "type": "string"
                },
                "repository_url": {
                    "type": "string"
                }
            }
        },
        "serializers.RunnerSerializer": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "last_contact": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "serializers.TokenSerializer": {
            "type": "object",
            "properties": {
                "expiration": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "serializers.UserSerializer": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "is_superuser": {
                    "type": "boolean"
                },
                "is_template_manager": {
                    "type": "boolean"
                },
                "last_name": {
                    "type": "string"
                }
            }
        },
        "serializers.WorkspaceSerializer": {
            "type": "object",
            "properties": {
                "config_source": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "environment_variables": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "git_source": {
                    "$ref": "#/definitions/serializers.GitWorkspaceSourceSerializer"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "runner": {
                    "$ref": "#/definitions/serializers.RunnerSerializer"
                },
                "status": {
                    "type": "string"
                },
                "template_version": {
                    "$ref": "#/definitions/serializers.WorkspaceTemplateVersionSerializer"
                },
                "type": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/serializers.UserSerializer"
                }
            }
        },
        "serializers.WorkspaceTemplateVersionSerializer": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "published": {
                    "type": "boolean"
                }
            }
        },
        "serializers.WorkspaceTypeSerializer": {
            "type": "object",
            "properties": {
                "config_files_default_path": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "supported_config_sources": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "targz.TarEntry": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "targz.TarTreeItem": {
            "type": "object",
            "properties": {
                "children": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/targz.TarTreeItem"
                    }
                },
                "full_path": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "templates.CreateTemplateRequestBody": {
            "type": "object",
            "required": [
                "name",
                "type"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "icon": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "templates.CreateTemplateVersionEntryRequestBody": {
            "type": "object",
            "required": [
                "path",
                "type"
            ],
            "properties": {
                "content": {
                    "type": "string"
                },
                "path": {
                    "description": "must start with a .",
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "templates.UpdateTemplateRequestBody": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "icon": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "templates.UpdateTemplateVersionEntryRequestBody": {
            "type": "object",
            "required": [
                "content",
                "path"
            ],
            "properties": {
                "content": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                }
            }
        },
        "templates.UpdateTemplateVersionRequestBody": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "config_file_path": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "minLength": 1
                },
                "published": {
                    "type": "boolean"
                }
            }
        },
        "workspaces.CreateWorkspaceRequestBody": {
            "type": "object",
            "required": [
                "config_source",
                "environment_variables",
                "name",
                "runner_id",
                "type"
            ],
            "properties": {
                "config_source": {
                    "type": "string"
                },
                "config_source_path": {
                    "type": "string"
                },
                "environment_variables": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "git_ref_name": {
                    "type": "string"
                },
                "git_repo_url": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "runner_id": {
                    "type": "integer"
                },
                "template_version_id": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "{{version_placeholder}}",
	Host:             "localhost:8080",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Codebox API",
	Description:      "Codebox server",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
