// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/templates": {
            "get": {
                "description": "List all templates",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "List templates",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.WorkspaceTemplate"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a template",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "Create template",
                "parameters": [
                    {
                        "description": "Template data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/templates.CreateTemplateRequestBody"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.WorkspaceTemplate"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/templates-by-name/:name": {
            "get": {
                "description": "Retrieve a template by name",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "Retrieve template by name",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Template name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.WorkspaceTemplate"
                        }
                    }
                }
            }
        },
        "/api/v1/templates/:id": {
            "get": {
                "description": "Retrieve a template by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "Retrieve template by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Template ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.WorkspaceTemplate"
                        }
                    }
                }
            }
        },
        "/api/v1/templates/:templateId": {
            "put": {
                "description": "List workspaces that use a template",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "List workspaces that use a template",
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Workspace"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a template",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "Delete template",
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.WorkspaceTemplate"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/templates/:templateId/latest-version": {
            "get": {
                "description": "Retrieve the latest template version",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "Retrieve the latest template version",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.WorkspaceTemplateVersion"
                        }
                    }
                }
            }
        },
        "/api/v1/templates/:templateId/versions": {
            "get": {
                "description": "List all template versions by template",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "List template versions by template",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.WorkspaceTemplateVersion"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/templates/:templateId/versions/:templateId/entries": {
            "post": {
                "description": "Create new template version entry",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "Create new template version entry",
                "parameters": [
                    {
                        "description": "Template version entry data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/templates.CreateTemplateVersionEntryRequestBody"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/targz.TarEntry"
                        }
                    }
                }
            }
        },
        "/api/v1/templates/:templateId/versions/:templateId/entries/:path": {
            "put": {
                "description": "Updates a template version entry",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "Updates a template version entry",
                "parameters": [
                    {
                        "description": "Template version entry data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/templates.UpdateTemplateVersionEntryRequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/targz.TarEntry"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete template version entry",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "Delete template version entry",
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/api/v1/templates/:templateId/versions/:versionId": {
            "get": {
                "description": "Retrieve template version by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "Retrieve template version by id",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.WorkspaceTemplateVersion"
                        }
                    }
                }
            },
            "put": {
                "description": "Update a template version",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "Update a template version",
                "parameters": [
                    {
                        "description": "Template version data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/templates.UpdateTemplateVersionRequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.WorkspaceTemplateVersion"
                        }
                    }
                }
            }
        },
        "/api/v1/templates/:templateId/versions/:versionId/entries": {
            "get": {
                "description": "List template version entries",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "List template version entries",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/targz.TarTreeItem"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/templates/:templateId/versions/:versionId/entries/:path": {
            "get": {
                "description": "Retrieve template version entry",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Templates"
                ],
                "summary": "Retrieve template version entry",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/targz.TarEntry"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.GitWorkspaceSource": {
            "type": "object",
            "properties": {
                "config_file_relative_path": {
                    "description": "path of the configuration files relative to the root of the repo",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "ref_name": {
                    "type": "string"
                },
                "repository_url": {
                    "type": "string"
                },
                "sourcesID": {
                    "type": "integer"
                }
            }
        },
        "models.Group": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "models.Runner": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "last_contact": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "public_url": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "use_public_url": {
                    "type": "boolean"
                }
            }
        },
        "models.User": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "groups": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Group"
                    }
                },
                "is_superuser": {
                    "type": "boolean"
                },
                "is_template_manager": {
                    "type": "boolean"
                },
                "last_name": {
                    "type": "string"
                }
            }
        },
        "models.Workspace": {
            "type": "object",
            "properties": {
                "config_source": {
                    "description": "template/git",
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "environment_variables": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "git_source": {
                    "$ref": "#/definitions/models.GitWorkspaceSource"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "runner": {
                    "$ref": "#/definitions/models.Runner"
                },
                "status": {
                    "type": "string"
                },
                "template_version": {
                    "$ref": "#/definitions/models.WorkspaceTemplateVersion"
                },
                "type": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/models.User"
                }
            }
        },
        "models.WorkspaceTemplate": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "icon": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "models.WorkspaceTemplateVersion": {
            "type": "object",
            "properties": {
                "config_file_relative_path": {
                    "type": "string"
                },
                "edited_on": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "published": {
                    "type": "boolean"
                },
                "published_on": {
                    "type": "string"
                },
                "template": {
                    "type": "integer"
                }
            }
        },
        "targz.TarEntry": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "targz.TarTreeItem": {
            "type": "object",
            "properties": {
                "children": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/targz.TarTreeItem"
                    }
                },
                "full_path": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "templates.CreateTemplateRequestBody": {
            "type": "object",
            "required": [
                "name",
                "type"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "icon": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "templates.CreateTemplateVersionEntryRequestBody": {
            "type": "object",
            "required": [
                "path",
                "type"
            ],
            "properties": {
                "content": {
                    "type": "string"
                },
                "path": {
                    "description": "must start with a .",
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "templates.UpdateTemplateRequestBody": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "icon": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "templates.UpdateTemplateVersionEntryRequestBody": {
            "type": "object",
            "required": [
                "content",
                "path"
            ],
            "properties": {
                "content": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                }
            }
        },
        "templates.UpdateTemplateVersionRequestBody": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "config_file_path": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "minLength": 1
                },
                "published": {
                    "type": "boolean"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
