definitions:
  models.WorkspaceTemplate:
    properties:
      description:
        type: string
      icon:
        type: string
      id:
        type: integer
      name:
        type: string
      type:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/templates:
    get:
      consumes:
      - application/json
      description: List all templates
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.WorkspaceTemplate'
            type: array
      security:
      - Codebox authentication token: []
      summary: List templates
      tags:
      - Templates
  /api/v1/templates/:id:
    get:
      consumes:
      - application/json
      description: Retrieve a template by id
      parameters:
      - description: Template ID
        in: path
        name: app
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.WorkspaceTemplate'
      security:
      - Codebox authentication token: []
      summary: Retrieve template by id
      tags:
      - Templates
swagger: "2.0"
