definitions:
  models.WorkspaceTemplate:
    properties:
      description:
        type: string
      icon:
        type: string
      id:
        type: integer
      name:
        type: string
      type:
        type: string
    type: object
  templates.CreateTemplateRequestBody:
    properties:
      description:
        type: string
      icon:
        type: string
      name:
        type: string
      type:
        type: string
    required:
    - name
    - type
    type: object
  templates.UpdateTemplateRequestBody:
    properties:
      description:
        type: string
      icon:
        type: string
      name:
        type: string
    required:
    - name
    type: object
info:
  contact: {}
paths:
  /api/v1/templates:
    get:
      consumes:
      - application/json
      description: List all templates
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.WorkspaceTemplate'
            type: array
      summary: List templates
      tags:
      - Templates
    post:
      consumes:
      - application/json
      description: Create a template
      parameters:
      - description: Template data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/templates.CreateTemplateRequestBody'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            items:
              $ref: '#/definitions/models.WorkspaceTemplate'
            type: array
      summary: Create template
      tags:
      - Templates
  /api/v1/templates/:id:
    get:
      consumes:
      - application/json
      description: Retrieve a template by id
      parameters:
      - description: Template ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.WorkspaceTemplate'
      summary: Retrieve template by id
      tags:
      - Templates
  /api/v1/templates/:templateId:
    put:
      consumes:
      - application/json
      description: Update a template
      parameters:
      - description: Template data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/templates.UpdateTemplateRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.WorkspaceTemplate'
            type: array
      summary: Update template
      tags:
      - Templates
swagger: "2.0"
