definitions:
  models.GitWorkspaceSource:
    properties:
      config_file_relative_path:
        description: path of the configuration files relative to the root of the repo
        type: string
      id:
        type: integer
      ref_name:
        type: string
      repository_url:
        type: string
      sourcesID:
        type: integer
    type: object
  models.Group:
    properties:
      createdAt:
        type: string
      id:
        type: integer
      name:
        type: string
      updatedAt:
        type: string
    type: object
  models.Runner:
    properties:
      id:
        type: integer
      last_contact:
        type: string
      name:
        type: string
      public_url:
        type: string
      type:
        type: string
      use_public_url:
        type: boolean
    type: object
  models.User:
    properties:
      email:
        type: string
      first_name:
        type: string
      groups:
        items:
          $ref: '#/definitions/models.Group'
        type: array
      is_superuser:
        type: boolean
      is_template_manager:
        type: boolean
      last_name:
        type: string
    type: object
  models.Workspace:
    properties:
      config_source:
        description: template/git
        type: string
      created_at:
        type: string
      environment_variables:
        items:
          type: string
        type: array
      git_source:
        $ref: '#/definitions/models.GitWorkspaceSource'
      id:
        type: integer
      name:
        type: string
      runner:
        $ref: '#/definitions/models.Runner'
      status:
        type: string
      template_version:
        $ref: '#/definitions/models.WorkspaceTemplateVersion'
      type:
        type: string
      updated_at:
        type: string
      user:
        $ref: '#/definitions/models.User'
    type: object
  models.WorkspaceTemplate:
    properties:
      description:
        type: string
      icon:
        type: string
      id:
        type: integer
      name:
        type: string
      type:
        type: string
    type: object
  models.WorkspaceTemplateVersion:
    properties:
      config_file_relative_path:
        type: string
      edited_on:
        type: string
      id:
        type: integer
      name:
        type: string
      published:
        type: boolean
      published_on:
        type: string
      template:
        type: integer
    type: object
  targz.TarEntry:
    properties:
      content:
        items:
          type: integer
        type: array
      name:
        type: string
      type:
        type: string
    type: object
  targz.TarTreeItem:
    properties:
      children:
        items:
          $ref: '#/definitions/targz.TarTreeItem'
        type: array
      full_path:
        type: string
      name:
        type: string
      type:
        type: string
    type: object
  templates.CreateTemplateRequestBody:
    properties:
      description:
        type: string
      icon:
        type: string
      name:
        type: string
      type:
        type: string
    required:
    - name
    - type
    type: object
  templates.CreateTemplateVersionEntryRequestBody:
    properties:
      content:
        type: string
      path:
        description: must start with a .
        type: string
      type:
        type: string
    required:
    - path
    - type
    type: object
  templates.UpdateTemplateRequestBody:
    properties:
      description:
        type: string
      icon:
        type: string
      name:
        type: string
    required:
    - name
    type: object
  templates.UpdateTemplateVersionEntryRequestBody:
    properties:
      content:
        type: string
      path:
        type: string
    required:
    - content
    - path
    type: object
  templates.UpdateTemplateVersionRequestBody:
    properties:
      config_file_path:
        type: string
      name:
        minLength: 1
        type: string
      published:
        type: boolean
    required:
    - name
    type: object
info:
  contact: {}
paths:
  /api/v1/templates:
    get:
      consumes:
      - application/json
      description: List all templates
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.WorkspaceTemplate'
            type: array
      summary: List templates
      tags:
      - Templates
    post:
      consumes:
      - application/json
      description: Create a template
      parameters:
      - description: Template data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/templates.CreateTemplateRequestBody'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            items:
              $ref: '#/definitions/models.WorkspaceTemplate'
            type: array
      summary: Create template
      tags:
      - Templates
  /api/v1/templates-by-name/:name:
    get:
      consumes:
      - application/json
      description: Retrieve a template by name
      parameters:
      - description: Template name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.WorkspaceTemplate'
      summary: Retrieve template by name
      tags:
      - Templates
  /api/v1/templates/:id:
    get:
      consumes:
      - application/json
      description: Retrieve a template by id
      parameters:
      - description: Template ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.WorkspaceTemplate'
      summary: Retrieve template by id
      tags:
      - Templates
  /api/v1/templates/:templateId:
    delete:
      consumes:
      - application/json
      description: Delete a template
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema:
            items:
              $ref: '#/definitions/models.WorkspaceTemplate'
            type: array
      summary: Delete template
      tags:
      - Templates
    put:
      consumes:
      - application/json
      description: List workspaces that use a template
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema:
            items:
              $ref: '#/definitions/models.Workspace'
            type: array
      summary: List workspaces that use a template
      tags:
      - Templates
  /api/v1/templates/:templateId/latest-version:
    get:
      consumes:
      - application/json
      description: Retrieve the latest template version
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.WorkspaceTemplateVersion'
      summary: Retrieve the latest template version
      tags:
      - Templates
  /api/v1/templates/:templateId/versions:
    get:
      consumes:
      - application/json
      description: List all template versions by template
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.WorkspaceTemplateVersion'
            type: array
      summary: List template versions by template
      tags:
      - Templates
  /api/v1/templates/:templateId/versions/:templateId/entries:
    post:
      consumes:
      - application/json
      description: Create new template version entry
      parameters:
      - description: Template version entry data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/templates.CreateTemplateVersionEntryRequestBody'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/targz.TarEntry'
      summary: Create new template version entry
      tags:
      - Templates
  /api/v1/templates/:templateId/versions/:templateId/entries/:path:
    delete:
      consumes:
      - application/json
      description: Delete template version entry
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      summary: Delete template version entry
      tags:
      - Templates
    put:
      consumes:
      - application/json
      description: Updates a template version entry
      parameters:
      - description: Template version entry data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/templates.UpdateTemplateVersionEntryRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/targz.TarEntry'
      summary: Updates a template version entry
      tags:
      - Templates
  /api/v1/templates/:templateId/versions/:versionId:
    get:
      consumes:
      - application/json
      description: Retrieve template version by id
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.WorkspaceTemplateVersion'
      summary: Retrieve template version by id
      tags:
      - Templates
    put:
      consumes:
      - application/json
      description: Update a template version
      parameters:
      - description: Template version data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/templates.UpdateTemplateVersionRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.WorkspaceTemplateVersion'
      summary: Update a template version
      tags:
      - Templates
  /api/v1/templates/:templateId/versions/:versionId/entries:
    get:
      consumes:
      - application/json
      description: List template version entries
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            items:
              $ref: '#/definitions/targz.TarTreeItem'
            type: array
      summary: List template version entries
      tags:
      - Templates
  /api/v1/templates/:templateId/versions/:versionId/entries/:path:
    get:
      consumes:
      - application/json
      description: Retrieve template version entry
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/targz.TarEntry'
      summary: Retrieve template version entry
      tags:
      - Templates
swagger: "2.0"
