name: Build

on:
  push:
    tags:
      - '*.*.*.*'

env:
  CGO_ENABLED: 0

jobs:
  build_server:
    runs-on: ubuntu-latest
    container: golang:1.23.1
    steps:
      - uses: actions/checkout@v4

      - name: 'Build backend'
        env:
          GOOS: linux
          GOARCH: amd64
        run: go build -o bin/codebox main.go

      - name: 'Upload Artifacts'
        uses: actions/upload-artifact@v4
        with:
          name: codebox-backend
          path: bin/codebox

  build_frontend:
    runs-on: ubuntu-latest
    container: node:20.12.2
    steps:
      - uses: actions/checkout@v4
      
      - name: 'Build frontend'
        env:
          CI: false
        run: |
          cd app
          npm i
          npm run build

      - name: 'Upload Artifacts'
        uses: actions/upload-artifact@v4
        with:
          name: codebox-frontend
          path: app/build/